# Generated by Django 5.1.4 on 2025-01-18 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=50)),
                ('section', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batch',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quizapp.batch')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Student',
            },
        ),
    ]
