# Generated by Django 5.1.4 on 2025-01-17 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'batch', 'verbose_name_plural': 'batchs'},
        ),
    ]
