# Generated by Django 5.1.6 on 2025-03-13 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subject',
            new_name='subjects',
        ),
    ]
