# Generated by Django 5.1.4 on 2025-02-03 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsapp', '0002_otp'),
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='auth_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='accountsapp.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='auth_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to='accountsapp.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='auth_users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='accountsapp.account'),
            preserve_default=False,
        ),
    ]
