# Generated by Django 5.1.6 on 2025-03-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_rename_subject_student_subjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='subjects',
            new_name='subject',
        ),
    ]
