# Generated by Django 5.1.4 on 2025-01-17 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_alter_batch_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batchs'},
        ),
    ]
