# Generated by Django 5.1.4 on 2025-01-21 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_remove_batch_section_remove_student_marks_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='quizapp.section'),
        ),
    ]
