# Generated by Django 5.1.4 on 2025-01-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_batch_options_alter_marks_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks',
            options={'verbose_name': 'Marks', 'verbose_name_plural': 'Marks'},
        ),
        migrations.AlterModelOptions(
            name='quizs',
            options={'verbose_name': 'Quizs', 'verbose_name_plural': 'Quizs'},
        ),
    ]
