# Generated by Django 5.1.6 on 2025-02-18 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_alter_batch_auth_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='auth_users',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='section', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
