# Generated by Django 5.1.6 on 2025-03-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_section_auth_users_alter_student_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='subject',
        ),
    ]
