# Generated by Django 5.1.4 on 2025-01-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_alter_marks_options_alter_quizs_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marks',
            new_name='Mark',
        ),
        migrations.RenameModel(
            old_name='Quizs',
            new_name='Quiz',
        ),
        migrations.AlterModelOptions(
            name='mark',
            options={'verbose_name': 'Mark', 'verbose_name_plural': 'Mark'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Student'},
        ),
    ]
