# Generated by Django 5.1.6 on 2025-03-08 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_subject_auth_users_subject_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='batch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='batch', to='quizapp.batch'),
            preserve_default=False,
        ),
    ]
