# Generated by Django 5.1.4 on 2025-01-17 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0006_rename_marks_mark_rename_quizs_quiz_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={'verbose_name': 'Batch', 'verbose_name_plural': 'Batch'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz', 'verbose_name_plural': 'Quiz'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Section'},
        ),
    ]
